export const categoryNames = [
    { id: "1", name: "Comedy" },
    { id: "2", name: "Education" },
    { id: "3", name: "Technology" },
    { id: "4", name: "Music" },
    { id: "5", name: "Travel" },
    { id: "6", name: "Gaming" },
    { id: "7", name: "Sports" },
    { id: "8", name: "News" },
    { id: "9", name: "Lifestyle" },
    { id: "10", name: "Science" },
    { id: "11", name: "Health" },
    { id: "12", name: "Business" },
    { id: "13", name: "Art" },
    { id: "14", name: "History" },
    { id: "15", name: "Nature" },
    { id: "16", name: "Fashion" },
    { id: "17", name: "Food" },
    { id: "18", name: "DIY" },
    { id: "19", name: "Animation" },
    { id: "20", name: "Spirituality" },
  ];
  
  export const mockVideos = [
    {
      id: "1",
      title: "Hướng dẫn React cơ bản",
      description: "Video hướng dẫn cách dùng React từ cơ bản đến nâng cao.",
      url: "https://example.com/videos/react-basic.mp4",
      thumbnail: "https://example.com/thumbnails/react-basic.jpg",
      duration: 600,
      uploadedAt: "2024-05-01T10:00:00Z",
      views: 1250,
      category: "Lập trình",
      visibility: "public", // viết thường
    },
    {
      id: "2",
      title: "Tạo API với Node.js và Express",
      description: "Video hướng dẫn cách tạo REST API đơn giản.",
      url: "https://example.com/videos/node-api.mp4",
      thumbnail: "https://example.com/thumbnails/node-api.jpg",
      duration: 720,
      uploadedAt: "2024-04-15T14:30:00Z",
      views: 980,
      category: "Lập trình",
      visibility: "unlisted",
    },
    {
      id: "3",
      title: "Những khoảnh khắc hài hước trên mạng",
      description: "Tổng hợp video hài hước viral nhất tuần qua.",
      url: "https://example.com/videos/funny-clips.mp4",
      thumbnail: "https://example.com/thumbnails/funny-clips.jpg",
      duration: 300,
      uploadedAt: "2024-04-28T08:45:00Z",
      views: 21500,
      category: "Giải trí",
      visibility: "public",
    },
    {
      id: "4",
      title: "Tin tức công nghệ 2025",
      description: "Tóm tắt những tin tức nổi bật trong ngành công nghệ đầu năm 2025.",
      url: "https://example.com/videos/tech-news.mp4",
      thumbnail: "https://example.com/thumbnails/tech-news.jpg",
      duration: 480,
      uploadedAt: "2025-01-01T09:00:00Z",
      views: 4200,
      category: "Tin tức",
      visibility: "private",
    },
  ];
  
  